export const SEARCH_ROOMS = "SEARCH_ROOMS";
export const SEARCH_LOCATIONS = "SEARCH_LOCATIONS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_ROOM_BY_ID = "GET_ROOM_BY_ID";
export const INSERT_ROOM = "INSERT_ROOM";
export const RESERVE_ROOM = "RESERVE_ROOM";
